<a href="https://colab.research.google.com/github/manjusri-NRI/python-mini-projects/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import random

In [56]:
from google.colab import drive

In [58]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [57]:
import pandas as pd

In [59]:
Datasetpath='/content/drive/MyDrive/retail_transactions.csv'

In [60]:
df=pd.read_csv(Datasetpath)

In [61]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [62]:
# Calculate total revenue
df["revenue"] = df["Quantity"] * df["Price"]
total_revenue = df["revenue"].sum()

print(f"Total Revenue: {total_revenue:,.2f}")

Total Revenue: 154,794.00

In [43]:
average_transcation_amount = df['revenue'].mean()
print(f"Average Transaction Amount: ₹{average_transcation_amount:,.2f}")

Average Transaction Amount: ₹1,547.94

In [63]:
df['ProductCategory'].mode()[0]

'Furniture'

In [64]:
amoungreaterthan200 = df['Price']>200

In [65]:
df[amoungreaterthan200]

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,revenue
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,634
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,2976
5,T006,2024-01-06,103,1836,515,Grocery,9,227,Debit,NaN,2043
7,T008,2024-01-08,101,1806,569,Toys,4,500,Debit,0.0,2000
8,T009,2024-01-09,101,1925,548,Apparel,7,217,Cash,10.0,1519
...,...,...,...,...,...,...,...,...,...,...,...
92,T093,2024-04-02,102,1408,519,Toys,1,433,Cash,10.0,433
94,T095,2024-04-04,103,1980,529,Electronics,7,309,Cash,NaN,2163
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,878
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,2395
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,1235

In [70]:
df.groupby('CustomerID')['Price'].sum().nlargest(3)

CustomerID
1396    799
1245    699
1734    543
Name: Price, dtype: int64